# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Johannes Müller
email: mue.johannes@icloud.com
description: > # this means to ignore newlines until "baseurl:"
  A site full of stuff I did, like and think about. So it's basically empty.
  But also a little playground to try stuff.

google_analytics: UA-76258012-1

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://joh-mue.github.io" # the base hostname & protocol for your site
twitter_username: joh_mue
github_username:  joh-mue

# Build settings
markdown: redcarpet

kramdown:
  input: GFM

collections:
  portfolio:
    output: true
    foo: bar